export { LoginPage } from './pages/LoginPage'
export { RegisterPage } from './pages/RegisterPage'
export { VerifyEmailPage } from './pages/VerifyEmailPage'
export { CompanySelectPage } from './pages/CompanySelectPage'
export { CreateCompanyPage } from './pages/CreateCompanyPage'
export { ForbiddenPage } from './pages/ForbiddenPage'
export { DashboardPage } from './pages/DashboardPage'
export { ContactsPage } from './pages/ContactsPage'
export { ContactFormPage } from './pages/ContactFormPage'
export { ContactDetailPage } from './pages/ContactDetailPage'
export { OrganizationsPage } from './pages/OrganizationsPage'
export { OrganizationFormPage } from './pages/OrganizationFormPage'
export { DealsPage } from './pages/DealsPage'
export { DealFormPage } from './pages/DealFormPage'
export { DealDetailPage } from './pages/DealDetailPage'
export { ActivitiesPage } from './pages/ActivitiesPage'
export { SettingsPage } from './pages/SettingsPage'
export { ReportsPage } from './pages/ReportsPage'
export { CalendarPage } from './pages/CalendarPage'
export { LeadsPage } from './pages/LeadsPage'
export { CotizacionesPage } from './pages/CotizacionesPage'
export { CotizacionFormPage } from './pages/CotizacionFormPage'
export { CotizacionDetailPage } from './pages/CotizacionDetailPage'
export { CotizacionPublicPage } from './pages/CotizacionPublicPage'
export { LeadFormPage } from './pages/LeadFormPage'
export { CuentasCobrarPage } from './pages/CuentasCobrarPage'
export { AlertasARPage } from './pages/AlertasARPage'
export { BillingPage } from './pages/BillingPage'

export { listarContactos, obtenerContacto, guardarContacto, eliminarContacto } from './data/contacts'
export { listarOrganizaciones, obtenerOrganizacion, guardarOrganizacion, eliminarOrganizacion } from './data/organizations'
export { listarDeals, obtenerDeal, guardarDeal, eliminarDeal, moverDeal } from './data/deals'
export { listarPipelines, guardarPipeline, eliminarPipeline, guardarStage, eliminarStage, reordenarStages } from './data/pipelines'
export { listarActividades, guardarActividad, eliminarActividad, toggleActividad } from './data/activities'
export { listarEventos, guardarEvento, eliminarEvento } from './data/eventos'
export { importarContactos } from './data/contacts'
export { importarOrganizaciones } from './data/organizations'
export { importarDeals } from './data/deals'
export { ImportCsvModal } from './components/ImportCsvModal'
export { downloadCSV } from './lib/exportData'
export { NotificationBell } from './components/NotificationDropdown'
export { AgendaButton } from './components/AgendaButton'
export { AgendaModal } from './components/AgendaModal'
export { crearNotificacion, crearNotificacionTodos } from './data/notifications'
export { obtenerWebhookToken, regenerarTokenWebhook, toggleWebhookActivo, listarLeads } from './data/leads'

export { NAV_SECTION_CRM } from './navItems'
