export { AuthContext, useAuth } from './auth/context'
export { AuthProvider } from './auth/AuthContext'
export { rolesFromSession } from './auth/rolesFromSession'
export { getPermissionsForRoles, PERMISSIONS, ROLES } from './auth/permissions'
export { hasPermission } from './auth/can'
export { getActiveCompanyId } from './auth/activeCompany'

export { ThemeContext, useTheme } from './theme/context'
export { ThemeProvider } from './theme/ThemeContext'
export { CompanyConfigContext, useCompanyConfig, DEFAULT_CONFIG } from './theme/companyConfigContext'
export { CompanyConfigProvider } from './theme/CompanyConfigProvider'

export { ErrorBoundary } from './components/ErrorBoundary'
export { Button } from './components/Button'
export { FormField } from './components/FormField'
export { Skeleton } from './components/Skeleton'
export { Can } from './components/Can'
export { ConfirmModal } from './components/ConfirmModal'
export { Logo } from './components/Logo'
export { PushPrompt } from './components/PushPrompt'
export { InstallPrompt } from './components/InstallPrompt'

export { getSupabase } from './lib/supabase'
export { usePlan, featureInfo, planLabel, checkQuotaBefore } from './data/plan'
export { FEATURES as PLAN_FEATURES, QUOTAS as PLAN_QUOTAS, PLAN_LABELS } from './data/planConfig'
export { UpgradeBanner } from './components/UpgradeBanner'
export { alertError, notify, confirmAction } from './lib/alert'
export { formatDate, formatDateTime } from './lib/formatDate'
export { formatMoney, MONEDA_POR_PAIS, formatearFecha } from './lib/formatMoney'
export { formatNumber, formatPercent } from './lib/formatNumber'
export { resolveTemplate, CONTEXT_VARIABLES, CONTEXT_OPTIONS } from './lib/resolveTemplate'
export { validarTaxId } from './lib/taxId'
export { setLocaleFromPais } from './i18n/index'

export { ProtectedRoute } from './routes/ProtectedRoute'
export { RequireCompany } from './routes/RequireCompany'
export { RequirePermission } from './routes/RequirePermission'

export { Sidebar } from './layouts/Sidebar'
export { AppLayout } from './layouts/AppLayout'
export { NAV_TOPS, NAV_SECTIONS_BASE } from './layouts/navItems'
export { NAV_SECTION_FINANZAS } from './layouts/navItemsFinanzas'
export { NAV_SECTION_CONSOLIDACION } from './layouts/navItemsConsolidacion'

export { default as i18n } from './i18n/index.js'
