export const PERMISSIONS = {
  CONTACT_VER: 'contact:ver',
  CONTACT_CREAR: 'contact:crear',
  CONTACT_EDITAR: 'contact:editar',
  CONTACT_ELIMINAR: 'contact:eliminar',
  ORGANIZATION_VER: 'organization:ver',
  ORGANIZATION_CREAR: 'organization:crear',
  ORGANIZATION_EDITAR: 'organization:editar',
  ORGANIZATION_ELIMINAR: 'organization:eliminar',
  DEAL_VER: 'deal:ver',
  DEAL_CREAR: 'deal:crear',
  DEAL_EDITAR: 'deal:editar',
  DEAL_ELIMINAR: 'deal:eliminar',
  PIPELINE_VER: 'pipeline:ver',
  PIPELINE_CREAR: 'pipeline:crear',
  PIPELINE_EDITAR: 'pipeline:editar',
  PIPELINE_ELIMINAR: 'pipeline:eliminar',
  ACTIVITY_VER: 'activity:ver',
  ACTIVITY_CREAR: 'activity:crear',
  REPORTE_VER: 'reporte:ver',
  USUARIO_VER: 'usuario:ver',
  USUARIO_CREAR: 'usuario:crear',
  USUARIO_EDITAR: 'usuario:editar',
  CONFIG_VER: 'config:ver',
  CONFIG_CREAR: 'config:crear',
  EVENTO_VER: 'evento:ver',
  EVENTO_CREAR: 'evento:crear',
  EVENTO_EDITAR: 'evento:editar',
  EVENTO_ELIMINAR: 'evento:eliminar',
  RRHH_APROBAR: 'rrhh:aprobar',
  NOMINA_VER: 'nomina:ver',
  NOMINA_CREAR: 'nomina:crear',
  NOMINA_APROBAR: 'nomina:aprobar',
  NOMINA_CONFIG: 'nomina:config',
}

export const ROLES = {
  admin: [
    PERMISSIONS.CONTACT_VER, PERMISSIONS.CONTACT_CREAR, PERMISSIONS.CONTACT_EDITAR, PERMISSIONS.CONTACT_ELIMINAR,
    PERMISSIONS.ORGANIZATION_VER, PERMISSIONS.ORGANIZATION_CREAR, PERMISSIONS.ORGANIZATION_EDITAR, PERMISSIONS.ORGANIZATION_ELIMINAR,
    PERMISSIONS.DEAL_VER, PERMISSIONS.DEAL_CREAR, PERMISSIONS.DEAL_EDITAR, PERMISSIONS.DEAL_ELIMINAR,
    PERMISSIONS.PIPELINE_VER, PERMISSIONS.PIPELINE_CREAR, PERMISSIONS.PIPELINE_EDITAR, PERMISSIONS.PIPELINE_ELIMINAR,
    PERMISSIONS.ACTIVITY_VER, PERMISSIONS.ACTIVITY_CREAR,
    PERMISSIONS.REPORTE_VER,
    PERMISSIONS.USUARIO_VER, PERMISSIONS.USUARIO_CREAR, PERMISSIONS.USUARIO_EDITAR,
    PERMISSIONS.CONFIG_VER, PERMISSIONS.CONFIG_CREAR,
    PERMISSIONS.EVENTO_VER, PERMISSIONS.EVENTO_CREAR, PERMISSIONS.EVENTO_EDITAR, PERMISSIONS.EVENTO_ELIMINAR,
    PERMISSIONS.RRHH_APROBAR,
    PERMISSIONS.NOMINA_VER, PERMISSIONS.NOMINA_CREAR, PERMISSIONS.NOMINA_APROBAR, PERMISSIONS.NOMINA_CONFIG,
  ],
  vendedor: [
    PERMISSIONS.CONTACT_VER, PERMISSIONS.CONTACT_CREAR, PERMISSIONS.CONTACT_EDITAR,
    PERMISSIONS.ORGANIZATION_VER, PERMISSIONS.ORGANIZATION_CREAR, PERMISSIONS.ORGANIZATION_EDITAR,
    PERMISSIONS.DEAL_VER, PERMISSIONS.DEAL_CREAR, PERMISSIONS.DEAL_EDITAR,
    PERMISSIONS.PIPELINE_VER,
    PERMISSIONS.ACTIVITY_VER, PERMISSIONS.ACTIVITY_CREAR,
    PERMISSIONS.EVENTO_VER, PERMISSIONS.EVENTO_CREAR,
  ],
  supervisor: [
    PERMISSIONS.CONTACT_VER, PERMISSIONS.CONTACT_CREAR, PERMISSIONS.CONTACT_EDITAR, PERMISSIONS.CONTACT_ELIMINAR,
    PERMISSIONS.ORGANIZATION_VER, PERMISSIONS.ORGANIZATION_CREAR, PERMISSIONS.ORGANIZATION_EDITAR, PERMISSIONS.ORGANIZATION_ELIMINAR,
    PERMISSIONS.DEAL_VER, PERMISSIONS.DEAL_CREAR, PERMISSIONS.DEAL_EDITAR, PERMISSIONS.DEAL_ELIMINAR,
    PERMISSIONS.PIPELINE_VER, PERMISSIONS.PIPELINE_CREAR, PERMISSIONS.PIPELINE_EDITAR,
    PERMISSIONS.ACTIVITY_VER, PERMISSIONS.ACTIVITY_CREAR,
    PERMISSIONS.REPORTE_VER,
    PERMISSIONS.EVENTO_VER, PERMISSIONS.EVENTO_CREAR, PERMISSIONS.EVENTO_EDITAR, PERMISSIONS.EVENTO_ELIMINAR,
    PERMISSIONS.RRHH_APROBAR,
    PERMISSIONS.NOMINA_VER,
  ],
  viewer: [
    PERMISSIONS.CONTACT_VER,
    PERMISSIONS.ORGANIZATION_VER,
    PERMISSIONS.DEAL_VER,
    PERMISSIONS.PIPELINE_VER,
    PERMISSIONS.ACTIVITY_VER,
    PERMISSIONS.EVENTO_VER,
  ],
}

export function getPermissionsForRoles(roles) {
  const set = new Set()
  for (const role of roles) {
    const perms = ROLES[role]
    if (perms) perms.forEach((p) => set.add(p))
  }
  return set
}
