export { listarCentros, guardarCentro, eliminarCentro, listarAlmacenes, guardarAlmacen, eliminarAlmacen, obtenerStock, listarStockGeneral, registrarMovimientoStock, listarMovimientos, transferirStock, listarUbicaciones, guardarUbicacion, eliminarUbicacion, obtenerValuacion } from './data/inventario'
export { CentrosPage } from './pages/CentrosPage'
export { AlmacenesPage } from './pages/AlmacenesPage'
export { InventarioPage } from './pages/InventarioPage'
export { ValuacionPage } from './pages/ValuacionPage'
export { MovimientosPage } from './pages/MovimientosPage'
export { TransferenciasPage } from './pages/TransferenciasPage'
export { KardexPage } from './pages/KardexPage'
export { ConteosPage } from './pages/ConteosPage'
export { ConteoDetailPage } from './pages/ConteoDetailPage'
export { UbicacionesPage } from './pages/UbicacionesPage'
export { TransportistasPage } from './pages/TransportistasPage'
export { PickingPage } from './pages/PickingPage'
export { PickingDetailPage } from './pages/PickingDetailPage'
export { RemitosPage } from './pages/RemitosPage'
export { RemitoDetailPage } from './pages/RemitoDetailPage'
export { crearPicking } from './data/picking'
