export { listarProveedores, obtenerProveedor, guardarProveedor, eliminarProveedor } from './data/proveedores'
export { listarOrdenes, obtenerOrden, guardarOrden, actualizarEstadoOrden } from './data/ordenesCompra'
export { listarMediosPago, guardarMedioPago, eliminarMedioPago, listarPagosProveedor, registrarPagoProveedor, eliminarPagoProveedor } from './data/pagosProveedor'
export { listarFacturasProveedor, obtenerFacturaProveedor, guardarFacturaProveedor, actualizarEstadoFactura, cotejarFactura } from './data/proveedorFacturas'

export { ProveedoresPage } from './pages/ProveedoresPage'
export { ProveedorFormPage } from './pages/ProveedorFormPage'
export { ProveedorDetailPage } from './pages/ProveedorDetailPage'
export { OrdenesCompraPage } from './pages/OrdenesCompraPage'
export { OrdenCompraFormPage } from './pages/OrdenCompraFormPage'
export { OrdenCompraDetailPage } from './pages/OrdenCompraDetailPage'
export { CalendarioPagosPage } from './pages/CalendarioPagosPage'
export { FacturasProveedorPage } from './pages/FacturasProveedorPage'
export { FacturaProveedorFormPage } from './pages/FacturaProveedorFormPage'
export { FacturaProveedorDetailPage } from './pages/FacturaProveedorDetailPage'
export { ScorecardsPage } from './pages/ScorecardsPage'
export { AlertasVencimientoPage } from './pages/AlertasVencimientoPage'
export { HistorialPreciosPage } from './pages/HistorialPreciosPage'
export { SugerenciasOCPage } from './pages/SugerenciasOCPage'
export { CuentasPagarPage } from './pages/CuentasPagarPage'
export { NAV_SECTION_SRM } from './navItems'
